### ISSUE TITLE
1- الرسالة النصية لقبول المسجل

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#100]
بعد الضغط على زر قبول للمسجل فان البرنامج يقوم بارسال الرسالة النصية التالية

تم تأكيد تسجيلكم في ملتقى الجمعيات الخيرية ولجان التنمية بمكة ، نأمل الإطلاع على فعاليات الملتقى عبر الموقع

Accept SMS fix.

**Comment by kossa** [comment]
Where is the account + Api :p

**Comment by hayyas** [comment]
سارسله لك بعد تفعيل الاشتراك ;)




تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:Where is the account + Api :p

**Comment by hayyas** [comment]
قمت بقبول هذا المسجل
http://moltaka-makkah.com/admin/registers/492/edit

لكن لم تصله رسالة نصية حتى الان

ايضا، مزود الخدمة لا يوجد فيه ارسال الرسالة
0547474093
