### ISSUE TITLE
2-  تقرير بأجوبة أسئلة التقييم

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#118]
في شاشة التقاريرالاحصائية نضيف التقرير التالي
Stacked Bar
وذلك لعرض الأجوبة لكل سؤال في التقييم حسب الترتيب

Survey report fix.

**Comment by kossa** [comment]
I'm waiting :)

**Comment by kossa** [comment]
We should run composer dump + composer seed on the original server ;)
