### ISSUE TITLE
اسم المسجل لا يظهر بشكل سليم

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#124]
اسم المسجل اذا كان طويل فلا يظهر بشكل سليم في حالتين
1- شاشة الشهادة
http://i.imgur.com/lUwJSbJ.png

2- عند الطباعة
http://i.imgur.com/kffOYp8.png

Name printing fix.

**Comment by kossa** [comment]
Just fixed 
Web : http://i.imgur.com/wdUywqb.png
Print : http://i.imgur.com/QB5fJk3.png

**Comment by hayyas** [comment]
I have an issue on the Print : http://i.imgur.com/FKxF9gt.png
It is ok on the web : http://i.imgur.com/AxmPRd1.png

**Comment by kossa** [comment]
I think problem of cache CSS

**Comment by hayyas** [comment]
the problem accoured by layout = landscape
now, it is fixed by layout = portrait

closed
