### ISSUE TITLE
على السيرفر الرئيسي لم تعطيني شاشة الشهادة

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#128]
على السيرفر الرئيسي للملتقى قمت بالتقييم بشكل سليم
ولكن شاشة الشهادة لم تظهر وتعطيني هذه رسالة الخطاء كالتالي
http://i.imgur.com/JYLRzAz.png

**Comment by kossa** [comment]
Ya akhi I created new table so I should run migration, and survey once we finish all :(
