### ISSUE TITLE
1-  اضافة فلتر في الشاشة الرئيسية

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#129]
اضافة فلتر في الشاشة الرئيسية حسب
الجنس - الوظيفة - المشاركة - الجهة - القاعة

**Comment by kossa** [comment]
We are using http://www.datatables.net/ so if someone wat to filter he can use the search box :)
Also we have Stats ;)

**Comment by hayyas** [comment]
لا لا..
لو اردت ان تحصل على : الرجال +  موظف فقط !!
كيف تفعل ??

لذا طلبوا الفلتر ليسهل عليهم ادارة بياناتهم ومتابعتها والاتصال على المسجلين ;)


تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:We are using http://www.datatables.net/ so if someone wat to filter he can use the search box :)
Also we have Stats ;)

**Comment by hayyas** [comment]
لو اردت ان تحصل على : الرجال +  موظف فقط !!
كيف تفعل ??

لذا طلبوا الفلتر ليسهل عليهم ادارة بياناتهم ومتابعتها والاتصال على المسجلين ;)

**Comment by hayyas** [comment]
كم تحتاج الوقت :)

**Comment by kossa** [comment]
For the moment I made  1H :'(

**Comment by hayyas** [comment]
الله يعطيك العافية.باذن الله حقك محفوظ :)



تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:Closed #129 via 600dd66.

**Comment by kossa** [comment]
2 H all :)

**Comment by hayyas** [comment]
Akhi :)
where is the filter !!

**Comment by kossa** [comment]
Att the bottom ;)
