### ISSUE TITLE
الرسالة النصية لتحضير المسجل

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#131]
بعد الضغط على زر تحضير للمسجل فان البرنامج يقوم بارسال الرسالة النصية التالية

Attendee SMS fix.

**Comment by kossa** [comment]
2 options : 
1. the mobile cannot read the Arabic Message
2. Impossible to get it bcz : http://i.imgur.com/gjSDmZD.png

**Comment by hayyas** [comment]
صدقني لم افهمك ابدا :)

انا عندي مشكلة بالانترنت وشابك على الجوال ..




تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:2 options : 
1. the mobile cannot read the Arabic Message
2. Impossible to get it bcz : http://i.imgur.com/gjSDmZD.png

**Comment by hayyas** [comment]
cancelled by customer
