### ISSUE TITLE
مشكلة - اذا اخطا المستخدم ولم يقم بالتسجيل فانه لا يستطيع التسجيل الا بعد تحديث كل الموقع

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#16]
مشكلة - اذا اخطا المستخدم ولم يقم بالتسجيل فانه لا يستطيع التسجيل الا بعد تحديث كل الموقع

re-load website fix

**Comment by kossa** [comment]
No I tried ;)

**Comment by hayyas** [comment]
اوكي as you see



تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:No I tried ;)
