### ISSUE TITLE
Registration roles & conditions fixes

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#2]
- رقم الهوية/الاقامة : يجب أن يكون 10 أرقام فقط
- رقم الهوية/الاقامة يجب أن يبدا برقم 1 أو برقم 2 فقط
- البريد الالكتروني يجب أن يحتوي على @ وعلى علامة النقطة(.) كحماية بسيطة
- رقم الجوال يجب أن يكون 10 أرقام فقط
- برقم الجوال يجب أن يبدأ بـرقمي 05 
- عند الضغط على زر تسجيل يجب التأكد من تعبئة جميع الحقول
All the fields are minatory.

Registration roles & conditions fixes.

**Comment by kossa** [comment]
I did everything except "All the fields are minatory"
