### ISSUE TITLE
تغيير الخط

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#20]
تغيير خط الموقع بمثل هذا الخط
www.arabicgit.com

Font fix.

**Comment by kossa** [comment]
Which font ?
"Git باللغة العربية!" or "نظام التحكم في النسخ الموزّع غير المركزي الآن له مرجعه باللغة العربية" ?

**Comment by hayyas** [comment]
Git باللغة العربية!


2015-02-06 12:40 GMT+03:00 Kouceyla <notifications@github.com>:

**Comment by kossa** [comment]
All website ?

**Comment by hayyas** [comment]
ما رايك نجعل المينيو + العناوين الرئيسية بالخط
Droid Arabic Kufi

وبقية الكلام والنصوص بالخط
Droid Arabic Naskh
