### ISSUE TITLE
تغيير الجزء الخاص بالبرومو و الجزء الخاص بالمعرض

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#21]
تغيير الجزء الخاص بالبرومو و الجزء الخاص بالمعرض كما في الصورة التالية

http://i.imgur.com/F7qWIzC.png

Navigation menu fixes.

**Comment by hayyas** [comment]
لم يتغير شيء بارك الله فيك
ممكن يوجد مشكلة في 
auto git-push

**Comment by kossa** [comment]
lol, we are working on : http://moltaka.your-new-it.com/ :D
