### ISSUE TITLE
تغيير الصورة والموقع

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#23]
في جزء اتصل بنا 
http://i.imgur.com/t6us7oL.png

تغيير الصورة الى
http://www.fairmont.com/assets/0/137/11406/11465/11467/15239/c3ff7313-b71f-4156-ba9c-b3f6924371db.jpg

وتغيير العنوان الى
https://www.google.com.sa/maps/dir/Makkah+Clock+Royal+Tower+Hotel/Makkah+Clock+Royal+Tower+Hotel,+Oum+Al+Qura+Street,King+Abdul+Aziz+Endowment,Abraj+Al+Bait+Complex,Makkah,+Mecca+24231/@21.4197118,39.7884791,13z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x0:0x8308e71b2bf1706a!2m2!1d39.825473!2d21.419636!1m5!1m1!1s0x15c204b7eaf25137:0x8308e71b2bf1706a!2m2!1d39.825473!2d21.419636

**Comment by kossa** [comment]
Give me the text of : http://i.imgur.com/ywDjXaq.png

**Comment by hayyas** [comment]
موجود في داخل ال issue 
:)




تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:Give me the text of : http://i.imgur.com/ywDjXaq.png

**Comment by hayyas** [comment]
نعم نعم
هنا  :)

https://github.com/kossa/moltaka-app/issues/33



2015-02-06 21:31 GMT+03:00 hayyas <hayyas.cs@gmail.com>:
