### ISSUE TITLE
أسئلة متكررة

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#27]
اضافة محتوى الأسئلة المتكررة كما يلي: 
http://i.imgur.com/WYESGaD.png

هل هناك رسوم للتسجيل في الملتقى ؟ 
لا يوجد رسوم للتسجيل في الملتقى.

هل الدعوة عامة ؟
الدعوة عامة لجميع أعضاء وموظفي اللجان والجمعيات الخيرية، والمقاعد محدودة.

هل يمكنني الحضور بمجرد التسجيل في الملتقى ؟ 
ستصلكم رسالة نصية بتأكيد لقبول تسجيلكم لان المقاعد محدودة.

هل هناك بطاقة للحضور ؟
نعم، يمكنكم طباعة بطاقة الحضور حالما يتم تأكيد تسجيلكم، أو الحضور في أول يوم ليقوم الموظف المختص بطباعة بطاقتكم.

هل يوجد شهادات للحضور ؟
نعم، هناك شهادات للحضور ويمكنكم طباعة شهادة الحضور الكترونيا من موقعنا الرسمي.

Q\A fix.

**Comment by kossa** [comment]
I need the text below ;)http://i.imgur.com/8Fm7Ngv.png

**Comment by hayyas** [comment]
you close it
https://github.com/kossa/moltaka-app/issues/28

:)
