### ISSUE TITLE
مشكلة عند الضغط على زر راسلنا

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#35]
عند الضغط على زر راسلنا
http://i.imgur.com/U1j9b2c.png

تظهر هذه المشكلة
http://i.imgur.com/LnjZbTE.png

Send email issue fix.

**Comment by kossa** [comment]
This is for newsletter, is not exists on our project ;)
we delete it ;)

**Comment by hayyas** [comment]
great :)

i see
you are right
