### ISSUE TITLE
تعديل نصوص رسالة الاخطاء بحيث تكون مفهومة

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#36]
تعديل نصوص رسالة الاخطاء بحيث تكون مفهومة مثلا:
identity = رقم الهوية/الاقامة

وذلك كما هو موجود في شاشة التسجيل

http://i.imgur.com/ljtHvMQ.png

text message description fixes.

**Comment by kossa** [comment]
I learned something awesome in laravel in this issue ;)
http://imgur.com/VETGtZo

**Comment by kossa** [comment]
I delete the 10 sec, if the user want to close the popup he can ;)

**Comment by hayyas** [comment]
okay no problem
