### ISSUE TITLE
4- ERD

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#4]
Field                *         Type              *         Mandatory              *         Note
................................................................................................................................ 
RequestID       *         int        *        P.K       *          start from 100
Name              *         chart     *      yes         *         Length = 100 charts
sex                  *         int         *      yes
identity            *         int         *       yes        *           (Length = 10) & (must start with 1 or 2)
education        *         int         *       yes
job                   *         int         *       yes
company         *         int         *       yes
email               *         char     *         yes
mobile             *         int        *        yes         *          (Length = 10) & (must start = 05)
city                  *         int         *       yes

**Comment by kossa** [comment]
sexe => string(10)
education => string(20)
job => string(10)
company => string(50)
mobile => string(10)
city => string(20)

to win time :)

**Comment by hayyas** [comment]
Yes no problem ;)




تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:sexe => string(10)
education => string(20)
job => string(10)
company => string(50)
mobile => string(10)
city => string(20)

to win time :)
