### ISSUE TITLE
اضافة صور وأسماء المتحدثين في الملتقى

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#50]
اضافة صور وأسماء المتحدثين في الملتقى
ارسلتها لك بالبريد

أ.د. علي النملة
أ.د. عدنان-البار
د. محمد محمود
د. عبدالله السدحان
د. صالح آل طالب
د. طلال أبو النور
د. خالد الحليبي
أ.د. يحي زمزمي
أ. ماهر أبو حجلة
م. باسم منشاوي
م. سعد المطرفي

Add speakers fix.

**Comment by hayyas** [comment]
المتحدثون الذين ليس لديهم صورة

https://www.iconfinder.com/icons/370076/account_avatar_client_male_manager_person_photo_picture_profile_user_icon#size=128

**Comment by kossa** [comment]
done with a972736a7adf42d858e69c36ad713ab0e662507d
