### ISSUE TITLE
3- Dash screen

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#57]
الشاشة الرئيسية بعد تسجيل الدخول

- حقل جديد في قاعدة البيانات باسم RoomID وذلك لتخزين رقم القاعة  :   + عند اختيار القاعة فانه يعمل Auto save
- حقل جديد في قاعدة البيانات باسم company2 وذلك لتخزين اسم الجهة اذا اختار المسجل: أخرى
- حقل جديد في قاعدة البيانات RequestStatus، وله القيم الثلاث: انتظار 0  -  قبول 1 - رفض 2
- حقل جديد في قاعدة البيانات للحضور AttendStatus: لم يحضر 0  - حضر 1
- عند الضغط على ايقونة + فانه يفتح له شاشة لتعديل البيانات مع زر حفظ

Wireframe:-
https://docs.google.com/drawings/d/1aB5LIJIjFujtOAb96lPeDD3AaNU93BBeFPCiaX5Hb-M/edit

عناصر الشاشة هنا
https://docs.google.com/spreadsheets/d/1TEEbErvz9hsDd__pOzw7KJq7ISaU9Ofg8irpNyD8jGQ/edit#gid=0

Dash screen fix.

**Comment by kossa** [comment]
Done
