### ISSUE TITLE
رقم القاعة يبدا من 0 أو فارغ

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#65]
رقم القاعة يبدا من 0 أو فارغ
وذلك للمسجلين الذين لا يريدون حضور ورشة عمل
:)

Workshop value fix.

**Comment by kossa** [comment]
hhhhh I did it Already

**Comment by hayyas** [comment]
في شاشة قائمة المسجلين لا يوجد 0 في القائمة
http://i.imgur.com/3Y6AVoW.png
