### ISSUE TITLE
مشكلة - الانتقال للصفحة 1 دائما بعد تحديث البيانات

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#68]
في شاشة قائمة المسجلين
عندما اقوم بتحديث المسجل رقم 40 في صفحة 4 بقبول او رفض او اختيار قاعة فانه بعد التحديث
يقوم البرنامج بعرض بيانات الصفحة رقم 1 وليس الصفحة رقم 4
http://i.imgur.com/2Kw9IPO.png

reload current page after updating the register fix.

**Comment by kossa** [comment]
I cannot do anything, we are using datatables :'(
