### ISSUE TITLE
صورة الموظف

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#73]
في شاشة الموظف هل ممكن نضيف رفع الصورة الشخصية
بحيث تظهر هنا
http://i.imgur.com/CJo6FI6.png

Employee image fix.

**Comment by kossa** [comment]
Is not in the project, and it takes a time ;)

**Comment by hayyas** [comment]
اوك ما يحتاج ;)



تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:Is not in the project, and it takes a time ;)
