### ISSUE TITLE
8- عدد المسجلين والمقبولين والمرفوضين والحضور

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#74]
اضافة مربعات الداشبورد في الشاشة الرئيسية
لعدد المسجلين والمقبولين والمرفوضين والحضور

Dashboard counter fix.

**Comment by kossa** [comment]
In all pages or only dash board ?

**Comment by hayyas** [comment]
only dash board :)




تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:In all pages or only dash board ?
