### ISSUE TITLE
تعديل بيانات موظف

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#75]
في شاشة الموظفين
- تفعيل الانتقال لبيانات الموظف والتعديل عليها اذا ضغط المستخدم على اسم الموظف

Employee edit fix.

**Comment by kossa** [comment]
Also not in our business project :p

**Comment by hayyas** [comment]
اوكي up to you
Just want it profissnal ;)




تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:Also not in our business project :p
