### ISSUE TITLE
اضافة تاريخ ووقت التسجيل للقراءة في شاشة المسجل

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#77]
اضافة تاريخ ووقت التسجيل للقراءة فقط لشاشة المسجل 
http://i.imgur.com/8YlfzNg.png

Registered date fix.

**Comment by kossa** [comment]
I made something cool ;)

**Comment by hayyas** [comment]
Coool 
or
Coold ;)




تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:I made something cool ;)
