### ISSUE TITLE
7- البحث بكلمة: لا غير صحيح

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#79]
البحث بجميع الكلمات جيد ما عدا البحث بكلمة: لا
http://i.imgur.com/WNycSuC.png

Search issue fix.

**Comment by kossa** [comment]
Alright I dont know why lol
We can sort the column :p

**Comment by hayyas** [comment]
اوكي جميل :)
اقفل الطلب وانا اخبرهم ليستخدموا الترتيب بدلا من البحث 




تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:Alright I dont know why lol
We can sort the column :p
