### ISSUE TITLE
4- حذف عامود الجهة الأخرى من جدول المسجلين في الشاشة الرئيسية

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#84]
حذف عامود الجهة الأخرى من جدول المسجلين في الشاشة الرئيسية
http://i.imgur.com/pp8Tw0Y.png

Delete other company column fix.

**Comment by kossa** [comment]
Really!!! lol

**Comment by hayyas** [comment]
يس ;)



تم الإرسال من جهاز Samsung اللوحيKouceyla <notifications@github.com> كتب:Really!!! lol
