### ISSUE TITLE
زر طباعة بطاقة الدخول الشخصية

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#96]
في الشاشة الرئيسية، في جدول المسجلين
اضافة عامود جديد يحتوي على زر لطباعة البطاقة الشخصية للمسجل

مقاس البطاقة : 8 * 3

البيانات : الاسم + الجهة + رقم التسجيل

التصميم : لا يوجد

Event card button fix.

**Comment by kossa** [comment]
We add a new link in the table ?

**Comment by hayyas** [comment]
I have update the issue :relieved:
