### ISSUE TITLE
التعديل على احصائية الجمعيات الخيرية

### ISSUE THREAD

**Issue by hayyas** [kossa/moltaka-app#98]
التعديل على احصائية الجمعيات الخيرية بعرض البيانات في جدول
بدلا من الحالي ليكون اوضح 

https://docs.google.com/drawings/d/11YDytx1wOGLEJbhN0suRkhkZwT92cay3fHrpY0VfqLA/edit?usp=sharing

Company report fix.

**Comment by kossa** [comment]
closed with 425c4e7

**Comment by hayyas** [comment]
ما شاء الله رووعة
